language: node_js
node_js:
  - node

dist: bionic
sudo: required

branches:
  only:
   - master

notifications:
  email:
    recipients:
      - dawnlum26@yahoo.com.sg
    on_success: always # default: change
    on_failure: always # default: always

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://dawnlumsy.github.io/weather-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/weather-app
  on: 
    branch: master